// Generated by CoffeeScript 1.6.3
(function() {
  (function($) {
    var $frame, $frameBottom, $frameLeft, $frameRight, $frameTop, createLoader, destroyLoader, hideLoader, showCreditsAndCopyRights, showLoading;
    $frame = $('.frame');
    $frameTop = $frame.children('.frameTop');
    $frameBottom = $frame.children('.frameBottom');
    $frameLeft = $frame.children('.frameLeft');
    $frameRight = $frame.children('.frameRight');
    createLoader = function() {
      $frameTop.append('<div class="loader"></div>');
      $frameBottom.append('<div class="loader"></div>');
      $frameLeft.append('<div class="loader"></div>');
      return $frameRight.append('<div class="loader"></div>');
    };
    showLoading = function() {
      var $frameBottomLoader, $frameLeftLoader, $frameRightLoader, $frameTopLoader;
      $frameTopLoader = $frameTop.children('.loader');
      $frameTopLoader.addClass('loading');
      $frameBottomLoader = $frameBottom.children('.loader');
      $frameBottomLoader.addClass('loading');
      $frameLeftLoader = $frameLeft.children('.loader');
      $frameLeftLoader.addClass('loading');
      $frameRightLoader = $frameRight.children('.loader');
      $frameRightLoader.addClass('loading');
      setTimeout(function() {
        return hideLoader($frameTopLoader, $frameBottomLoader, $frameLeftLoader, $frameRightLoader);
      }, 6000);
      return setTimeout(function() {
        return destroyLoader($frameTopLoader, $frameBottomLoader, $frameLeftLoader, $frameRightLoader);
      }, 7000);
    };
    showCreditsAndCopyRights = function() {
      var $copyRights, $credits;
      $copyRights = $('.copyrights');
      $credits = $('.credits');
      $copyRights.fadeIn('slow');
      return $credits.fadeIn('slow');
    };
    hideLoader = function(toploader, bottomloader, leftloader, rightloader) {
      toploader.fadeOut('slow');
      bottomloader.fadeOut('slow');
      leftloader.fadeOut('slow');
      rightloader.fadeOut('slow');
      return showCreditsAndCopyRights();
    };
    destroyLoader = function(toploader, bottomloader, leftloader, rightloader) {
      toploader.remove();
      bottomloader.remove();
      leftloader.remove();
      return rightloader.remove();
    };
    $(document).ready(function() {
      return createLoader();
    });
    return $(window).load(function() {
      return showLoading();
    });
  })(jQuery);

}).call(this);

/*
//@ sourceMappingURL=loader.map
*/
